#!/bin/sh

set -e

case "$1" in
    purge)
        userdel selenium-server || true
        rm -rf /var/lib/selenium-server /var/log/selenium-server /var/run/selenium-server
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d selenium-server remove >/dev/null
fi
# End automatically added section


exit 0
